# yaml-language-server: $schema=../../schema.json
apiVersion: v1alpha1
kind: ctfer.io/Dynamic
spec:
  name: Arm Strong
  description: |
    It seems that there was a secret conversation between Commander Neil Armstrong and Houston before that "famous saying".
  attribution: 4n74r3s
  value: 500
  minimum: 50
  decay: 275
  function: logarithmic
  state: visible

  flags:
    - csawctf{7bYhky_0n3_5m411_5h311c0d3_f0r_1nj3ct10n_qokqum_0n3_914n7_ch41n_f0r_r0p_zybdyr}

  files:
    - infra/chal

  connection_info: |
    nc chals.ctf.csaw.io 21003
