# yaml-language-server: $schema=../../schema.json
apiVersion: v1alpha1
kind: ctfer.io/DynamicIaC
spec:
  name: Space Portal
  description: |
    This portal in space can teleport your ship to anywhere you want!
    Interact with it in a special way, but watch out for aliens!
  attribution: 4n74r3s
  value: 500
  minimum: 50
  decay: 275
  function: logarithmic
  state: visible

  flags:
    - csawctf{jyqBum_9r347_waxcok_d3v1c3_d38u9_pr070c01_3v3n_w0rk5_1n_7h3_un1v3r53_2xicde}

  files:
    - infra/chal

  shared: true
  start: true
  scenario:
    apiVersion: v1alpha1
    kind: sdk.ctfer.io/manual
    spec:
      reference: common/aws-monopod-tcp:v0.1.0
    outputs:
      connection_info: |
        {{- $hostport := index .URLs "21000/TCP" -}}
        {{- $parts := splitList ":" $hostport -}}
        {{- $host := "" -}}
        {{- $port := "" -}}

        {{- if ge (len $parts) 1 -}}
          {{- $host = index $parts 0 -}}
        {{- end -}}

        {{- if ge (len $parts) 2 -}}
          {{- $port = index $parts 1 -}}
        {{- end -}}

        {{- if and $host $port -}}
        nc {{ $host }} {{ $port }}
        {{- else -}}
        # Host or port not available: {{ $hostport }}
        {{- end -}}
    additional:
      image: 391919513406.dkr.ecr.us-east-1.amazonaws.com/rev/space-portal:v0.1.0 # XXX manual effort here
      port: '21000'
      hostname: chals.ctf.csaw.io
      minReplicas: '1'
      maxReplicas: '10'
